name: 🚦 candi-backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs:
      classification:
        description: "Classification of the repository"
        required: true
        type: string
        default: "app-api"

permissions:
  security-events: write
  packages: write
  contents: read
  pull-requests: write


env:
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COVERAGE_THRESHOLD: "80"

jobs:
  ci:
    uses: ARYAVERS/aryavars-ci/.github/workflows/app.yml@main
    with:
      classification: "app-api"
    secrets: inherit

    #Retriger